# Generated by Django 5.1.2 on 2024-12-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortalTrabajador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupomuscular',
            name='region',
            field=models.CharField(choices=[('superior', 'Superior'), ('inferior', 'Inferior')], max_length=20),
        ),
    ]
