# Generated by Django 5.1.2 on 2024-11-24 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Horario', models.CharField(max_length=50)),
                ('Actividad', models.CharField(max_length=50)),
                ('Maquinas_Diponibles', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('plan', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Membresias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Precio', models.IntegerField(default=0)),
                ('Horario1', models.CharField(max_length=50)),
                ('Horario2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Metricas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.IntegerField(null=True)),
                ('peso', models.IntegerField(null=True)),
                ('peso_press_banca', models.IntegerField(null=True)),
                ('peso_press_inclinado', models.IntegerField(null=True)),
                ('peso_fondos', models.IntegerField(null=True)),
                ('peso_jalon_al_pecho', models.IntegerField(null=True)),
                ('peso_remo_polea', models.IntegerField(null=True)),
                ('peso_remo_libre', models.IntegerField(null=True)),
                ('peso_dominada', models.IntegerField(null=True)),
                ('peso_sentadilla_libre', models.IntegerField(null=True)),
                ('peso_sentadilla_bulgara', models.IntegerField(null=True)),
                ('peso_maquina_cuadriceps', models.IntegerField(null=True)),
                ('peso_maquina_isquiotibiales', models.IntegerField(null=True)),
                ('peso_gemelos', models.IntegerField(null=True)),
                ('peso_biceps_mancuerna', models.IntegerField(null=True)),
                ('peso_triceps_mancuerna', models.IntegerField(null=True)),
                ('peso_elevaciones_laterales', models.IntegerField(null=True)),
                ('peso_elevaciones_laterales_posterior', models.IntegerField(null=True)),
                ('peso_press_militar', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PortalCMAS.cliente')),
            ],
        ),
    ]
