# Generated by Django 5.1.2 on 2024-11-28 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortalCMAS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricascliente',
            name='altura',
        ),
    ]
