# Generated by Django 5.1.2 on 2024-12-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortalCMAS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupomuscular',
            name='region',
            field=models.CharField(choices=[('superior', 'Superior'), ('inferior', 'Inferior')], default='superior', max_length=20),
        ),
        migrations.AlterField(
            model_name='grupomuscular',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
