# Generated by Django 5.1.1 on 2024-11-27 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortalCMAS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='rut',
            new_name='rut_usuario',
        ),
    ]
