# Generated by Django 5.1.2 on 2024-11-20 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortalCMAS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterModelManagers(
            name='cliente',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='username',
        ),
        migrations.AlterField(
            model_name='registroentrada',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PortalCMAS.cliente'),
        ),
    ]
