# Generated by Django 5.1.2 on 2024-11-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortalCMAS', '0002_remove_metricascliente_altura'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricasejercicioscliente',
            name='series',
            field=models.IntegerField(null=True),
        ),
    ]
