# Generated by Django 5.1.2 on 2024-12-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortalCMAS', '0002_grupomuscular_region_alter_grupomuscular_nombre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ejercicio',
            new_name='Ejercicios',
        ),
    ]
